version: '3.9'
services: 
    redis:
        image: "redis:alpine" 
    mongodb:
        image: "mongo"
    web:
        build:
            context: src/HepsiFlyCaseStudy
            dockerfile: ../../dockerfile
        restart: always
        depends_on:
            - mongodb
            - redis
        environment:
            ASPNETCORE_ENVIRONMENT: Prod
    nginx:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - web
        ports:
            - 80:80